language: php

php:
  - "5.5"
  - "5.4"
  - "5.3"

before_script:
  - composer install
  - git config --global user.email "test@example.com"
  - git config --global user.name "Test User"

script:
  - sh ./sh/run-tests.sh

notifications:
  email:
    - andy@dev.next-step-software.com

